services:
  school-event-manager-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
     GROQ_API_KEY: ${GROQ_API_KEY:-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}